language: python
python:
  - "3.7"
services:
  - docker
before_install:
  - docker build -t someshkoli/improved-winter .
# command to run tests
script:
  - docker run someshkoli/improved-winter
  - pytest
