language: python
python:
  - "3.7"
services:
  - docker
after_script:
  - docker build -t someshkoli/improved-winter .
# command to run tests
script:
  - pytest
  - docker run someshkoli/improved-winter
